-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_campaign_tree`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_campaign_tree
-- *
-- * Campaign Tree
-- *
-- *******************************************************/
CREATE TABLE `civicrm_campaign_tree` (
  `campaign_id` int unsigned NOT NULL COMMENT 'Unique Campaign ID',
  `path` varchar(255) NOT NULL COMMENT 'Tree Node path',
  `depth` int unsigned NOT NULL COMMENT 'Tree Node depth',
  PRIMARY KEY (`campaign_id`),
  CONSTRAINT FK_civicrm_campaign_tree_campaign_id FOREIGN KEY (`campaign_id`) REFERENCES `civicrm_campaign`(`id`) ON DELETE CASCADE
)
ENGINE=InnoDB;
